name: greetings_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  cloud_firestore: ^3.4.4
  provider: ^6.0.3
  google_sign_in: ^5.4.1
  fluttertoast: ^8.0.9
  path_provider: ^2.0.11

  # Utility Packages
  cached_network_image: ^3.2.2
  shimmer: ^2.0.0


  # UI Packages
  flutter_staggered_grid_view: ^0.6.2
  google_nav_bar: ^5.0.6
  line_awesome_flutter: ^2.0.0
  font_awesome_flutter: ^10.2.1


  #To save edit images
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.1.0
  share: ^2.0.1 
  zoom_widget: ^0.2.1
  image_picker: ^0.8.5+3
  flutter_colorpicker: ^1.0.3
  extended_image: ^6.2.1
  crop: ^0.5.2
  image: ^3.2.0
  image_editor: ^1.0.2
  colorfilter_generator: ^0.0.8
  hand_signature: ^2.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
